---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 9/8/2020 9:36 AM
---

local stx_character_creation = {
    name = "",
    lastName = "",
    age = 20,
    currentCharacterModel = { fathersID = 0, mothersID = 0, skinColor = 0, shapeMix = 0.0,
                              eyesColor = 0, eyebrowsHeight = 0, eyebrowsWidth = 0, noseWidth = 0,
                              noseHeight = 0, noseLength = 0, noseBridge = 0, noseTip = 0, noseShift = 0,
                              cheekboneHeight = 0, cheekboneWidth = 0, cheeksWidth = 0, lips = 0, jawWidth = 0,
                              jawHeight = 0, chinLength = 0, chinPosition = 0,
                              chinWidth = 0, chinShape = 0, neckWidth = 0,
                              hairModel = 4, firstHairColor = 0, secondHairColor = 0, eyebrowsModel = 0, eyebrowsColor = 0,
                              beardModel = -1, beardColor = 0, chestModel = -1, chestColor = 0, blushModel = -1, blushColor = 0, lipstickModel = -1, lipstickColor = 0,
                              blemishesModel = -1, ageingModel = -1, complexionModel = -1, sundamageModel = -1, frecklesModel = -1, makeupModel = -1 }
}

function changeGender(model)
    local mhash = GetHashKey(model)
    while not HasModelLoaded(mhash) do
        RequestModel(mhash)
        Citizen.Wait(10)
    end

    if HasModelLoaded(mhash) then
        SetPlayerModel(PlayerId(), mhash)
        SetPedMaxHealth(PlayerPedId(), 400)
        SetEntityHealth(PlayerPedId(), 400)
        SetModelAsNoLongerNeeded(mhash)
    end
end

function refreshDefaultCharacter()
    SetPedDefaultComponentVariation(PlayerPedId())
    ClearAllPedProps(PlayerPedId())
    if GetEntityModel(PlayerPedId()) == GetHashKey("mp_m_freemode_01") then
        SetPedComponentVariation(PlayerPedId(), 3, 8, 0, 2)
        SetPedComponentVariation(PlayerPedId(), 4, 4, 4, 2)
        SetPedComponentVariation(PlayerPedId(), 6, 1, 0, 2)
        SetPedComponentVariation(PlayerPedId(), 8, 15, 0, 2)
        SetPedComponentVariation(PlayerPedId(), 11, 225, 0, 2)
    else
        SetPedComponentVariation(PlayerPedId(), 3, 1, 0, 2)
        SetPedComponentVariation(PlayerPedId(), 4, 0, 0, 2)
        SetPedComponentVariation(PlayerPedId(), 6, 1, 1, 2)
        SetPedComponentVariation(PlayerPedId(), 8, 2, 0, 2)
        SetPedComponentVariation(PlayerPedId(), 11, 235, 0, 2)
    end
end

function UpdateFace(eyebrowsHeight, eyebrowsWidth, noseWidth, noseHeight, noseLength, noseBridge, noseTip
, noseShift, cheekboneHeight, cheekboneWidth, cheeksWidth, lips, jawWidth, jawHeight, chinLength, chinPosition, chinWidth, neckWidth)

    local ped = PlayerPedId()
   --SetPedEyeColor(ped, eyesColor)
    SetPedFaceFeature(ped, 6, eyebrowsHeight)
    SetPedFaceFeature(ped, 7, eyebrowsWidth)
    SetPedFaceFeature(ped, 0, noseWidth)
    SetPedFaceFeature(ped, 1, noseHeight)
    SetPedFaceFeature(ped, 2, noseLength)
    SetPedFaceFeature(ped, 3, noseBridge)
    SetPedFaceFeature(ped, 4, noseTip)
    SetPedFaceFeature(ped, 5, noseShift)
    SetPedFaceFeature(ped, 8, cheekboneHeight)
    SetPedFaceFeature(ped, 9, cheekboneWidth)
    SetPedFaceFeature(ped, 10, cheeksWidth)
    SetPedFaceFeature(ped, 12, lips)
    SetPedFaceFeature(ped, 13, jawWidth)
    SetPedFaceFeature(ped, 14, jawHeight)
    SetPedFaceFeature(ped, 15, chinLength)
    SetPedFaceFeature(ped, 16, chinPosition)
    SetPedFaceFeature(ped, 17, chinWidth)
    --SetPedFaceFeature(ped, 18, chinShape)
    SetPedFaceFeature(ped, 19, neckWidth)

end

RegisterNUICallback('ChangeGender', function(data, cb)
    if stx_character_creation.currentCharacterModel.gender ~= data.gender then
        if data.gender == "1" then
            changeGender("mp_f_freemode_01")
        end
        if data.gender == "0" then
            changeGender("mp_m_freemode_01")
        end
        refreshDefaultCharacter()
        stx_character_creation.currentCharacterModel.gender = data.gender
        return cb('ok')
    end
    cb('error')
end)

RegisterNUICallback('charDataOverlay', function(data, cb)
    local Blemishes = data[1]
    local beard = data[2]
    local eyeBrows = data[3]
    local againg = data[4]
    local makeup = data[5]
    local freckles = data[6]
    local complexion = data[7]
    local sunDamage = data[8]
    local lipstickModel =data[9]
    local blush = data[10]
    local chestHair = data[11]
    local bodyBlemishes = data[12]
    local moreBodyBlemish = data[13]


    local ped = PlayerPedId()
    SetPedHeadOverlay(ped, 0, Blemishes, 0.99)
    SetPedHeadOverlay(ped, 1, beard, 0.99)
    SetPedHeadOverlay(ped, 2, eyeBrows, 0.99)
    SetPedHeadOverlay(ped, 3,againg, 0.99)
    SetPedHeadOverlay(ped, 4, makeup, 0.99)
    SetPedHeadOverlay(ped, 5, blush, 0.99)
    SetPedHeadOverlay(ped, 6, complexion, 0.99)
    SetPedHeadOverlay(ped, 7, sunDamage, 0.99)
    SetPedHeadOverlay(ped, 8, lipstickModel, 0.99)
    SetPedHeadOverlay(ped, 9, freckles, 0.99)
    SetPedHeadOverlay(ped, 10, chestHair, 0.99)
    SetPedHeadOverlay(ped, 11, bodyBlemishes, 0.99)
    SetPedHeadOverlay(ped, 12, moreBodyBlemish, 0.99)
    SetPedHeadOverlayColor(ped, 0, 0, 0, 0)
    SetPedHeadOverlayColor(ped, 3, 0, 0, 0)
    SetPedHeadOverlayColor(ped, 6, 0, 0, 0)
    SetPedHeadOverlayColor(ped, 7, 0, 0, 0)
    SetPedHeadOverlayColor(ped, 9, 0, 0, 0)
    SetPedHeadOverlayColor(ped, 4, 0, 0, 0)

end)

RegisterNUICallback('charDataParents', function(data, cb)
    SetPedHeadBlendData(PlayerPedId(), data[1], data[2], data[3], data[4], data[5], data[6], data[7], data[8], data[9], data[10])
end)
RegisterNUICallback('charDataFace', function(data, cb)
    local noseWidth = data[1]
    local noseHeight = data[2]
    local noseLength = data[3]
    local noseBridgeShift = data[4]
    local noseTrip = data[5]
    local noseShift = data[6]
    local eyesBrowWidth = data[7]
    local eyesBrowHeight = data[8]
    local cheekboneHeight = data[9]
    local cheekboneWidth = data[10]
    local cheeksWidth = data[11]
    local eyeState = data[12] --TODO
    local lips = data[13]
    local jawWidth = data[14]
    local jawHeight = data[15]
    local chinLength = data[16]
    local chinPosition = data[17]
    local chinWidth = data[18]
    local neckWidth = data[19]

    UpdateFace(eyesBrowWidth, eyesBrowHeight, noseWidth,noseHeight,noseLength, noseBridgeShift, noseTrip,noseShift, cheekboneHeight, cheekboneWidth, cheeksWidth, lips,jawWidth, jawHeight, chinLength,chinLength,chinPosition,chinWidth,chinShape, neckWidth)
end)


RegisterNUICallback('charDataEyeColor', function(data, cb)
    local eyeColor =tostring(data * 1.0)

    SetPedEyeColor(PlayerPedId(),eyeColor)
        --TODO NAO FUNCIONA
end)

RegisterNUICallback('charDataOverlayColor', function(data, cb)
    local ped = PlayerPedId()

    SetPedHeadOverlayColor(ped, 1, 0, data[1].color, data[1].color2)
    SetPedHeadOverlayColor(ped, 2, 1, data[2].color, data[2].color2)
    SetPedHeadOverlayColor(ped, 3, 1, data[3].color, data[3].color2)
    SetPedHeadOverlayColor(ped, 4, 0, data[4].color, data[4].color2)
    SetPedHeadOverlayColor(ped, 5, 2, data[5].color, data[5].color2)
    SetPedHeadOverlayColor(ped, 6, 0, data[6].color, data[6].color2)
    SetPedHeadOverlayColor(ped, 7, 0, data[7].color, data[7].color2)
    SetPedHeadOverlayColor(ped, 8, 2, data[8].color, data[8].color2)
    SetPedHeadOverlayColor(ped, 9, 0, data[9].color, data[9].color2)
    SetPedHeadOverlayColor(ped, 10, 1, data[10].color, data[10].color2)
    SetPedHeadOverlayColor(ped, 11, 0, data[11].color, data[11].color2)
    SetPedHeadOverlayColor(ped, 12, 0, data[12].color, data[12].color2)
end)

RegisterNUICallback('charDataHairColor', function(data, cb)
    print('charDataHairColor')
    print(json.encode(data))
end)

RegisterNUICallback('charDataHair', function(data, cb)
    print("charDataHair")
    print(json.encode(data))
end)

Citizen.CreateThread(function()
    SetNuiFocus(true, true)
    changeGender("mp_m_freemode_01")
    stx_character_creation.currentCharacterModel.gender = 1
    refreshDefaultCharacter()


end)

