---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 9/8/2020 9:43 AM
---

fx_version 'bodacious'
game 'gta5'

ui_page "html/menus/creator/index.html"

files {
    "html/menus/creator/index.html",
    "html/menus/creator/css/style.css",
    "html/css/material.min.css",
    "html/css/font-awesome.min.css",
    "html/js/jquery.js",
    "html/menus/creator/js/creator.min.js",
    "html/fonts/*",
    "html/images/creator/*.png",
    "html/**/**/**/**",
    "html/**/**/**",
    "html/**/**",
    "html/**",
}

client_scripts {
    "client.lua"
}

--[[
server_scripts {
    "@vrp/lib/utils.lua",
    "server.lua"
}]]
