---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 6/20/2020 8:39 PM
---

-- Resource Metadata
fx_version 'bodacious'
games { 'gta5' }

author 'ImagicTheCat and Muulfz'
description 'A Roleplay Framework'
version '1.0.0'

client_scripts {
    "lib/utils.lua",
    "client/base.lua",
    "client/iplloader.lua",
    "client/player_state.lua",
    "client/survival.lua",
    "client/map.lua",
    "client/identity.lua",
    "client/basic_garage.lua",
    "client/police.lua",
    "client/admin.lua",
    "client/basic_phone.lua",
    "client/basic_radio.lua"
}

server_scripts {
    "lib/utils.lua",
    "permissions.lua",
    "base.lua",
    "modules/storage/database.lua",
    "modules/gui.lua",
    "modules/group.lua",
    "modules/admin.lua",
    "modules/survival.lua",
    "modules/player_state.lua",
    "modules/map.lua",
    "modules/money.lua",
    "modules/inventory.lua",
    "modules/identity.lua",
    "modules/business.lua",
    "modules/item_transformer.lua",
    "modules/emotes.lua",
    "modules/police.lua",
    "modules/home.lua",
    "modules/home_components.lua",
    "modules/mission.lua",
    "modules/aptitude.lua",
    "modules/chat.lua",

    -- basic implementations
    "modules/basic_gunshop.lua",
    "modules/basic_garage.lua",
    "modules/basic_items.lua",
    "modules/basic_radio.lua",
    "modules/base_menu/*.lua",
    "modules/commands/*.lua",
    "modules/model/*.lua"
}

-- client files
files {
    "lib/Tunnel.lua",
    "lib/Proxy.lua",
    "lib/Debug.lua",
    "lib/Luaseq.lua",
    "lib/Tools.lua",
    "cfg/client.lua",
    "gui/static/js/*.js",
    "gui/static/js/*.js.map",
    "gui/asset-manifest.json",
    "gui/*.js",
    "gui/index.html",
    "gui/oldInterface/*.js",
    "gui/oldInterface/*.css"
--[[    "gui/index.html",
    "gui/design.css",
    "gui/main.js",
    "gui/Menu.js",
    "gui/ProgressBar.js",
    "gui/WPrompt.js",
    "gui/RequestManager.js",
    "gui/AnnounceManager.js",
    "gui/Div.js",
    "gui/dynamic_classes.js",
    --"gui/AudioEngine.js",
    --"gui/lib/libopus.wasm.js",
    "gui/images/voice_active.png",
    "gui/sounds/phone_dialing.ogg",
    "gui/sounds/phone_ringing.ogg",
    "gui/sounds/phone_sms.ogg",
    "gui/sounds/radio_on.ogg",
    "gui/sounds/radio_off.ogg"]]
}


