---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/22/2020 9:37 PM
---


RegisterNetEvent('OpenLoja')
AddEventHandler('OpenLoja', function()
    SendNUIMessage({ action = "open" })
    SetNuiFocus(true, true)
end)

RegisterNetEvent('OpenCarros')
AddEventHandler('OpenCarros', function()
    SendNUIMessage({ action = "loja" })
    SetNuiFocus(true, true)
end)


Citizen.CreateThread(function()
    SetNuiFocus(false, false)
end)
