---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/22/2020 9:41 PM
---
---
RegisterCommand('OpenLoja', function(source, args, raw)
    TriggerClientEvent('OpenLoja', source)
end, false)

RegisterCommand('OpenCarros', function(source, args, raw)
    TriggerClientEvent('OpenCarros', source)
end, false)