---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/12/2020 9:13 PM
---

local function ch_kick(player, choice)
    local user_id = vRP.getUserId(player)

    local id = vRP.prompt(player, "User id to kick: ", "")
    local reason = vRP.prompt(player, "Reason: ", "")

    if vRP.adminKick(user_id, id, reason) then
        vRPclient._notify(player, "kicked user " .. id)
    end
end

local function ch_coords(player, choice)
    local user_id = vRP.getUserId(player)

    if vRP.adminCoordinates(user_id) then
    end
end

local function ch_noclip(player, choice)
    vRPclient._toggleNoclip(player)
end

vRP.registerMenuBuilder("main", function(add, data)
    local user_id = vRP.getUserId(data.player)
    if user_id then
        local choices = {}

        -- build admin menu
        choices["Admin_Legacy"] = { function(player, choice)
            local menu = vRP.buildMenu("admin", { player = player })
            menu.name = "Admin"
            menu.css = { top = "75px", header_color = "rgba(200,0,0,0.75)" }
            menu.onclose = function(player)
                vRP.openMainMenu(player)
            end -- nest menu

            if vRP.hasPermission(user_id, "player.kick") then
                menu["@Kick"] = { ch_kick }
            end
            if vRP.hasPermission(user_id, "player.coords") then
                menu["@Coords"] = { ch_coords }
            end
            if vRP.hasPermission(user_id, "player.noclip") then
                menu["@Noclip"] = { ch_noclip }
            end
            vRP.openMenu(player, menu)
        end }

        add(choices)
    end
end)