---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 9/10/2020 9:15 PM
---
local Tunnel = module("lib/Tunnel")
t_stx_character_inventory = {}
Tunnel.bindInterface("stx_character_inventory", t_stx_character_inventory)

t_stx_character_inventory = Tunnel.getInterface("stx_character_inventory")

function t_stx_character_inventory.OpenInventory(inventory)
    print(json.encode(inventory))
    SendNUIMessage({
        event = "CreateNewInventory",
        data = inventory
    }
    )
end

RegisterNetEvent("t_stx_character_inventory.OpenInventory")
AddEventHandler("t_stx_character_inventory.OpenInventory", function(inventory)
    SetNuiFocus(true, true)
    SendNUIMessage({
        event = "CreateNewInventory",
        data = inventory
    }
    )
end)

Citizen.CreateThread(function()
    SetNuiFocus(false, false)


end)