---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/19/2020 9:50 PM
---

-- Resource metadata
fx_version 'bodacious'
game 'gta5'

author 'STX Academy'
description 'STX Performance and Graphic options'
version '1.0.0'


ui_page "html/index.html"

-- What to run
client_script {
    "script/client.lua",
}

server_script {
    "script/server.lua"
}
files {
    "html/index.html",
    "html/css/style.css",
    "html/img/cars/*.png",
    "html/img/*.png",
    "html/img/*.jpg",
    "html/js/script.js"
}

