---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 9/10/2020 9:28 PM
---

Inventory = {

}

function Inventory:new(name, maxWeight)
    local inventoryTable = {
        id = math.random(0, 2000),
        name = name,
        weight = 0,
        maxWeight = maxWeight,
        slotNumber = 12 + (4 * math.floor(maxWeight / 10)),
        slots = {}
    }

    for i = 1, inventoryTable.slotNumber do
        table.insert(inventoryTable.slots, i, {
            isEmpty = true
        })
    end

    return inventoryTable
end

function Inventory:AddItem(inventory, itemTable, quantity)
    for i = 1, inventory.slotNumber do
        if inventory.slots[i].isEmpty then
            Inventory:SetSlotItem(inventory, i, itemTable, quantity)
            return true
        end
    end
    return false
end

function Inventory:RemoveItem(inventory, slotId, quantity)
    local item = inventory.slots[slotId]

    if item.quantity >= quantity and not item.isEmpty then
        if item.quantity <= quantity then
            inventory.slots[slotId] = Inventory:GenerateEmptySlot()
        else
            item.quantity = item.quantity - quantity
        end
        inventory.weight = inventory.weight - (inventory.weight * quantity)

        return true
    end
    return true
end

function Inventory:SetSlotItem(inventory, slotId, itemTable, quantity)
    if inventory.slots[slotId].isEmpty then
        inventory.slots[slotId] = itemTable
        inventory.weight = inventory.weight + (inventory.slots[slotId].weight * quantity)
    end
end

function Inventory.GenerateEmptySlot()
    return {
        isEmpty = true
    }
end

InventoryItem = {}

function InventoryItem:new(itemName, itemMaxStack, isUsable, isDrop, img, weight)
    local InventoryItemTable = {
        itemName = itemName,
        itemMaxStack = itemMaxStack,
        isUsable = isUsable,
        isDrop = isDrop,
        img = img,
        weight = weight,
    }

    return InventoryItemTable
end